# Generated by Django 3.2 on 2022-02-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220209_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetfile',
            name='tweep',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='tweep',
        ),
    ]
