# Generated by Django 3.2 on 2022-02-10 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220209_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texts', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='images', to='post.Image')),
            ],
            options={
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='file_content',
        ),
        migrations.DeleteModel(
            name='TweetFile',
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
